FROM node:12.2.0 as build-node
WORKDIR /front
COPY . .
RUN npm install
RUN npm run build --prod
FROM nginx:1.15
COPY --from=build-node /front/dist/front/ /usr/share/nginx/html
COPY --from=build-node /front/ /etc/nginx/conf.d/
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
