FROM node:12.2.0 as build-node
WORKDIR /front
COPY . .
RUN npm install
RUN npm run build --prod
RUN npm install express
FROM nginx:1.15
COPY default.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY dist/front .
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
